#
# AzuraCast Docker Compose Configuration File
#
# When updating, you will be prompted to replace this file with a new
# version; you should do this whenever possible to take advantage of
# new updates.
#
# If you need to customize this file, you can create a new file named:
#   docker-compose.override.yml
# with any changes you need to make.
#
version : '2.2'

services :
  nginx_proxy :
    container_name : nginx_proxy
    image : "azuracast/azuracast_nginx_proxy:${AZURACAST_VERSION:-latest}"
    ports :
      - '${AZURACAST_HTTP_PORT:-80}:80'
      - '${AZURACAST_HTTPS_PORT:-443}:443'
    volumes :
      - letsencrypt:/etc/nginx/certs
      - nginx_proxy_vhosts:/etc/nginx/vhost.d
      - letsencrypt_html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment :
      NGINX_TIMEOUT : ${NGINX_TIMEOUT:-1800}
      DEFAULT_HOST : ${LETSENCRYPT_HOST:-azuracast.local}
    networks :
      - frontend
    depends_on :
      - web
    restart : always

  nginx_proxy_letsencrypt :
    container_name : nginx_proxy_letsencrypt
    image : "azuracast/azuracast_nginx_proxy_letsencrypt:${AZURACAST_VERSION:-latest}"
    volumes_from :
      - nginx_proxy
    volumes :
      - letsencrypt_acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment :
      DEFAULT_EMAIL : ${LETSENCRYPT_EMAIL}
    networks :
      - frontend
    restart : always

  web :
    container_name : azuracast_web
    image : "azuracast/azuracast_web_v2:${AZURACAST_VERSION:-latest}"
    # Want to customize the HTTP/S ports? Follow the instructions here:
    # https://docs.azuracast.com/en/administration/docker#using-non-standard-ports
    ports :
      - '${AZURACAST_SFTP_PORT:-2022}:2022'
    depends_on :
      - mariadb
      - stations
      - redis
    env_file : azuracast.env
    environment :
      LANG : ${LANG:-en_US.UTF-8}
      AZURACAST_DC_REVISION : 11
      AZURACAST_VERSION : ${AZURACAST_VERSION:-latest}
      AZURACAST_SFTP_PORT : ${AZURACAST_SFTP_PORT:-2022}
      VIRTUAL_HOST : ${LETSENCRYPT_HOST:-azuracast.local}
      NGINX_TIMEOUT : ${NGINX_TIMEOUT:-1800}
      LETSENCRYPT_HOST : ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL : ${LETSENCRYPT_EMAIL}
    volumes :
      - letsencrypt:/etc/nginx/certs:ro
      - www_vendor:/var/azuracast/www/vendor
      - tmp_data:/var/azuracast/www_tmp
      - station_data:/var/azuracast/stations
      - shoutcast2_install:/var/azuracast/servers/shoutcast2
      - geolite_install:/var/azuracast/geoip
      - sftpgo_data:/var/azuracast/sftpgo/persist
      - backups:/var/azuracast/backups
    networks :
      - frontend
      - backend
    restart : always
    ulimits : &default-ulimits
      nofile :
        soft : 65536
        hard : 65536
    logging : &default-logging
      options :
        max-size : "1m"
        max-file : "5"

  mariadb :
    container_name : azuracast_mariadb
    image : "azuracast/azuracast_db:${AZURACAST_VERSION:-latest}"
    volumes :
      - db_data:/var/lib/mysql
    env_file : azuracast.env
    networks :
      - backend
    restart : always
    logging : *default-logging

  redis :
    container_name : azuracast_redis
    image : "azuracast/azuracast_redis:${AZURACAST_VERSION:-latest}"
    sysctls :
      net.core.somaxconn : 1024
    volumes :
      - redis_data:/data
    networks :
      - backend
    restart : always
    logging : *default-logging

  stations :
    container_name : azuracast_stations
    image : "azuracast/azuracast_radio:${AZURACAST_VERSION:-latest}"
    ports :
      # This default mapping is the outgoing and incoming ports for the first 50 stations.
      # You can override this port mapping in your own docker-compose.override.yml file.
      # For instructions, see:
      # https://docs.azuracast.com/en/administration/docker#expanding-the-station-port-range
      - '8000:8000'
      - '8005:8005'
      - '8006:8006'
      - '8010:8010'
      - '8015:8015'
      - '8016:8016'
      - '8020:8020'
      - '8025:8025'
    volumes :
      - station_data:/var/azuracast/stations
      - shoutcast2_install:/var/azuracast/servers/shoutcast2
      - letsencrypt:/etc/nginx/certs
      - tmp_data:/var/azuracast/www_tmp
    networks :
      - frontend
      - backend
    init : true
    restart : always
    ulimits : *default-ulimits
    logging : *default-logging

networks :
  frontend :
    driver : bridge
  backend :
    driver : bridge

volumes :
  nginx_proxy_vhosts : { }
  db_data : { }
  letsencrypt : { }
  letsencrypt_html : { }
  letsencrypt_acme : { }
  shoutcast2_install : { }
  geolite_install : { }
  sftpgo_data : { }
  station_data : { }
  www_vendor : { }
  tmp_data : { }
  redis_data : { }
  backups : { }
